version: '2.1'

services:

  docker-volume-ipfs:
    build:
      context: .
      dockerfile: Dockerfile.${ARCH}
    container_name: docker-volume-ipfs
    hostname: docker-volume-ipfs
    image: sofwerx/docker-volume-ipfs:${ARCH}
    environment:
      ARCH: ${ARCH}
    volumes:
      - /:/chroot

